apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mood-sensors-apis
  description: APIs to interact with the mood-sensors component
spec:
  type: openapi
  lifecycle: development
  owner: dekt-dev-team2
  system: devx-mood
  definition: 
   $text: https://github.com/dektlong/mood-sensors/blob/dev/config/backstage/apis/mood-sensors-swagger.yaml